### PR TITLE
Add validation pattern for entities and enums properties "Name", "PluralName"

### PR DESCRIPTION
**Pull request by nocturne732**

### CODE REVIEW

**Review by bacr — CHANGES_REQUESTED** [review]
You've added validators on client side, but form is still submitted, even with validation errors. Let's remove validators on client side and add them on server side instead.

**Comment by nocturne732** [comment]
> You've added validators on client side, but form is still submitted, even with validation errors. Let's remove validators on client side and add them on server side instead.

I've made changes following by your comments

**Comment by nocturne732** [comment]
> This name is not explaining their objective

Deleted.

**Comment by yamaoto** [comment]
> 
> 
> > You've added validators on client side, but form is still submitted, even with validation errors. Let's remove validators on client side and add them on server side instead.
> 
> I've made changes following by your comments

You need to move validation to their validation classes, CreateEntityValidator and UpdateEntityValidator, for Entity and CreateEnumValidator and UpdateEnumValidator for enum

**Comment by bacr** [comment]
Fixed myself

**Pull request closed without merging**
